#!/system/bin/sh

bb=/sbin/bb/busybox

# cpu, sched and cache tweaks
$bb echo 350000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
$bb echo 350000 > /sys/devices/system/cpu/cpu0/cpufreq/screen_off_max_freq
$bb echo 1200000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
$bb echo 1 > /sys/devices/system/cpu/cpu0/cpufreq/gpu_oc
$bb echo 2 > /sys/devices/system/cpu/sched_mc_power_savings
$bb echo 15000000 > /proc/sys/kernel/sched_latency_ns
$bb echo 2000000 > /proc/sys/kernel/sched_min_granularity_ns
$bb echo 3000000 > /proc/sys/kernel/sched_wakeup_granularity_ns

# block tweaks
for i in /sys/block/*/queue ; do
  $bb echo 0 > $i/iostats
  $bb echo 0 > $i/rotational
done

$bb echo 0 > /sys/block/mmcblk0/queue/add_random
$bb echo 1 > /sys/block/mmcblk0/queue/rq_affinity

# adjust f2fs ram threshold
if [ -e /sys/fs/f2fs ] ; then
  $bb echo 5 > /sys/fs/f2fs/mmcblk0p10/ram_thresh
  $bb echo 5 > /sys/fs/f2fs/mmcblk0p11/ram_thresh
  $bb echo 25 > /sys/fs/f2fs/mmcblk0p12/ram_thresh
fi
